apiVersion: machinelearning.seldon.io/v1alpha2
engine:
  resources:
    requests:
      cpu: "0.1"
model:
  annotations:
    seldon.io/engine-log-message-type: seldon.message.pair
    seldon.io/engine-log-messages-externally: "false"
    seldon.io/engine-log-requests: "false"
    seldon.io/engine-log-responses: "false"
    seldon.io/headless-svc: "false"
    deployment_version: "v1"
  env:
    MODEL_NAME: model-name
  image:
    name: argonhiisi/seldon-core-microservice:latest
    pullPolicy: IfNotPresent
  name: classifier
  resources:
    requests:
      memory: 1Mi
name: my-model
oauth:
  key: null
  secret: null
predictorLabels:
  fluentd: "true"
  version: v1
replicas: 1
sdepLabels:
  app: seldon
