---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-1
  annotations:
    volume.beta.kubernetes.io/storage-class: "my-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi

