apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-claim
  namespace: seldon-app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
